### ISSUE TITLE
📝  Adding support for Mermaid to Gatsby

### ISSUE THREAD

**Issue by thetrevorharmon** [thetrevorharmon/thetrevorharmon.com#157]
Would be useful to write about https://github.com/thetrevorharmon/thetrevorharmon.com/pull/156. Other resources require chromium (including current [gatsby plugin](https://www.gatsbyjs.com/plugins/gatsby-remark-mermaid/))

**Comment by thetrevorharmon** [comment]
Netlify support: https://github.com/thetrevorharmon/thetrevorharmon.com/commit/1cb6137d20dd29c5e2325de77962ab21ad6d7260

```log
12:59:03 PM: Error: Could not find Chromium (rev. 1108766). This can occur if either
12:59:03 PM:  1. you did not perform an installation before running the script (e.g. `npm install`) or
12:59:03 PM:  2. your cache path is incorrectly configured (which is: /opt/buildhome/.cache/puppeteer).
12:59:03 PM: For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
12:59:03 PM:     at ChromeLauncher.resolveExecutablePath (file:///opt/build/repo/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:263:27)
12:59:03 PM:     at ChromeLauncher.executablePath (file:///opt/build/repo/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:176:25)
12:59:03 PM:     at ChromeLauncher.computeLaunchArguments (file:///opt/build/repo/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:93:37)
12:59:03 PM:     at async ChromeLauncher.launch (file:///opt/build/repo/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:57:28)
12:59:03 PM:     at async run (file:///opt/build/repo/node_modules/@mermaid-js/mermaid-cli/src/index.js:433:19)
12:59:03 PM:     at async cli (file:///opt/build/repo/node_modules/@mermaid-js/mermaid-cli/src/index.js:179:3)
```

**Comment by thetrevorharmon** [comment]
```log
An unexpected error occurred: "ENOENT: no such file or directory, symlink '../../lib/cjs/main-cli.js' -> '/opt/buildhome/.yarn_cache/v4/npm-@puppeteer-browsers-0.5.0-1a1ee454b84a986b937ca2d93146f25a3fe8b670/node_modules/@puppeteer/browsers/.bin/@puppeteer/browsers'".
```

**Comment by thetrevorharmon** [comment]
https://www.gatsbyjs.com/plugins/gatsby-remark-mermaid/

- Very thin wrapper around `remark-mermaidjs`
- doesn't include puppeteer out of the box (which isn't a dealbreaker)
- doesn't support caching

Might be interesting to explore this plugin and see if making a PR on it would make sense

**Comment by thetrevorharmon** [comment]
Looking at the way remark-mermaidjs is configured, it basically just renders everything and then grabs the mermaid blocks. Doesn't specifically look for the `\`\`\`mermaid` header.

Also, things are pretty buried in the Gatsby plug-in. Making a PR is a no-go for caching (probably).

Also, maintaining local code means I can strip out the styles and use my own

**Comment by thetrevorharmon** [comment]
Used [mermaid-cli](https://github.com/mermaid-js/mermaid-cli)

Tried to use the `run` command via the node wrapper

```
import { run } from "@mermaid-js/mermaid-cli"

await run(
   "input.mmd", "output.svg", // {optional options},
)
```

Had issues with that, it wouldn't recognize the file correctly. Ended up going with the "install locally" option

```
yarn add @mermaid-js/mermaid-cli
./node_modules/.bin/mmdc -h
```

**Comment by thetrevorharmon** [comment]
I write a bunch of temp files because all of the command line arguments require files. When the process is done, I grab the string version of the svg as the thing to return.

I decided to return svg bc it's styleable and beats an image or pdf in terms of rendering

I added an option to remove the default mermaid css because I find it to be ugly and I wanted to include my own to follow my theme

**Comment by thetrevorharmon** [comment]
Gatsby makes it pretty easy to do caching. I debated about the "right" way to determine if a node needs to be re-generated but in the end I landed on a hash of the mermaid code as the way to tell if it needs to be rebuilt. If the hash changes, it shouldn't read the value from the cache but instead it should generate a new svg.

The problem is that it orphans entries in the cache because of the way the key is generated. I might try to solve this at some point, but the solution for now is to recreate the cache if it gets too big. That seems unlikely to be a problem in production, so I'm fine with it

**Comment by thetrevorharmon** [comment]
Gatsby makes it really easy to do local plugins—just add a plug-in with the right naming scheme to the `plugins/` directory and you're off to the races. There is even a plug-in init script to create it for you. If you follow the structure, referencing a plug-in in the Gatsby-config is just a manner of putting the name of the plug-in. Super easy

**Comment by thetrevorharmon** [comment]
To get netlify support
- had to move the default cache directory of puppeteer. Sticking it in `.cache` caused it to be overwritten by Gatsby. The default location was outside the project directory and caused path errors. Went with `.cache-puppeteer`
- had to use the netlify cache plug-in and explicitly set the netlify cache to include `.cache-puppeteer`
